CREATE TABLE [dbo].[Account]
(
	[AccountId] VARCHAR(100) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Balance] INT NOT NULL,
	[Status] VARCHAR(10) NOT NULL,
	[MemberName] VARCHAR(50) NOT NULL FOREIGN KEY (MemberName) REFERENCES Member(Name)
)
